MEASURE_DICT = {
    'MP' :  ' mê ga píc seo ',
    'byte' :  ' bai ',
    'KB' :  ' ki lô bai ',
    'MB' :  ' mê ga bai ',
    'Mb' :  ' mê ga bai ',
    'mb' :  ' mê ga bai ',
    'Gb' :  ' ghi ga bai ',
    'GB' :  ' ghi ga bai ',
    'gb' :  ' ghi ga bai ',
    'TB' :  ' tê ra bai ',
    'Tb' :  ' tê ra bai ',
    'km' :  ' ki lô mét ',
    'm' :  ' mét ',
    'cm' :  ' xen ti mét ',
    'mm' :  ' mi li mét ',
    'nm' :  ' na nô mét ',
    'ha' :  ' héc ta ',
    'L' :  ' lít ',
    'l' :  ' lít ',
    'ml' :  ' mi li lít ',
    'kg' :  ' ki lô gam ',
    'Kg' :  ' ki lô gam ',
    'g' :  ' gam ',
    'gram' :  ' gờ ram ',
    'gr' :  ' gờ ram ',
    'mg' :  ' mi li gam ',
    'W' :  ' goát ',
    'kW' :  ' ki lô goát ',
    'VND' :  ' việt nam đồng ',
    'vnd' :  ' việt nam đồng ',
    'đ ' :  ' đồng ',
    'K' :  ' nghìn ',
    'k' :  ' nghìn ',
    'tr' :  ' triệu ',
    'usd' :  ' u ét đê ',
    'eur' :  ' ơ rô ',
    'Eur' :  ' ơ rô '
}