UNITS_DICT = { 
	"bpm" : " nhịp trên phút ",
	"nm/s" : " na nô mét trên giây ",
	"µm/s" : " mi cờ rô mét trên giây ",
	"mm/s" : " mi li mét trên giây ",
	"cm/s" : " xen ti mét trên giây ",
	"dm/s" : " đề xi mét trên giây ",
	"dam/s" : " đề ca mét trên giây ",
	"hm/s" : " héc tô mét trên giây ",
	"km/s" : " ki lô mét trên giây ",
	"m/s" : " mét trên giây ",
	"nm/giây" : " na nô mét trên giây ",
	"µm/giây" : " mi cờ rô mét trên giây ",
	"mm/giây" : " mi li mét trên giây ",
	"cm/giây" : " xen ti mét trên giây ",
	"dm/giây" : " đề xi mét trên giây ",
	"dam/giây" : " đề ca mét trên giây ",
	"hm/giây" : " héc tô mét trên giây ",
	"km/giây" : " ki lô mét trên giây ",
	"m/giây" : " mét trên giây ",
	"nm/h" : " na nô mét trên giờ ",
	"µm/h" : " mi cờ rô mét trên giờ ",
	"mm/h" : " mi li mét trên giờ ",
	"cm/h" : " xen ti mét trên giờ ",
	"dm/h" : " đề xi mét trên giờ ",
	"dam/h" : " đề ca mét trên giờ ",
	"hm/h" : " héc tô mét trên giờ ",
	"km/h" : " ki lô mét trên giờ ",
	"kmh" : " ki lô mét trên giờ ",
	"m/h" : " mét trên giờ ",
	"nm/giờ" : " na nô mét trên giờ ",
	"µm/giờ" : " mi cờ rô mét trên giờ ",
	"mm/giờ" : " mi li mét trên giờ ",
	"cm/giờ" : " xen ti mét trên giờ ",
	"dm/giờ" : " đề xi mét trên giờ ",
	"dam/giờ" : " đề ca mét trên giờ ",
	"hm/giờ" : " héc tô mét trên giờ ",
	"km/giờ" : " ki lô mét trên giờ ",
	"m/giờ" : " mét trên giờ ",
	"m3/h" : " mét khối trên giờ ",
	"mAh" : " mi li am pe giờ ",
	"kWh/ngày" : " ki lô goát giờ trên ngày ",
	"/tấn" : " trên tấn ",
	"/thùng" : " trên thùng ",
	"/căn" : " trên căn ",
	"/cái" : " trên cái ",
	"/con" : " trên con ",
	"/lần" : " trên lần ",
	"/năm" : " trên năm ",
	"/tháng" : " trên tháng ",
	"/ngày" : " trên ngày ",
	"/giờ" : " trên giờ ",
	"/phút" : " trên phút ",
	"đ/CP" : " đồng trên cổ phiếu ",
	"đ/lít" : " đồng trên lít ",
	"đ/lượt" : " đồng trên lượt ",
	"người/" : " người trên ",
	"giờ/" : " giờ trên ",
	'%':'phần trăm',
	'mAh':'mi li am pe',
	" lít/" : " lít trên ",
	"./" : "",
	"Nm" : " Niu tơn mét ",
	"º" : " độ ",
	# "vòng 1/" : " vòng 1 ",
	"mmol/l" : " mi li mon trên lít ",
	"mg/" : " mi li gam trên ",
	# "g/" : " gam trên ",
	"kg/" : " ki lô gam trên ",
	"cái/" : " cái trên ",
	"triệu/" : " triệu trên ",
	"g/km" : " gam trên ki lô mét ",
	"ounce" : " ao ",
	"m3/s" : " mét khối trên giây ",
	'byte':'bai',
	'KB':'ki lô bai',
	'Mb':'mê ga bai',
	'MB':'mê ga bai',
	'Gb':'ghi ga bai',
	'GB':'ghi ga bai',
	'gb':'ghi ga bai',
	'TB':'tê ra bai',
 
	# Unit of volume 
	'dm3':'đề xi mét khối',
	'cm3':'xen ti mét khối',
	'm3':'mét khối',
	#'2G':'hai gờ',
	#'3G':'ba gờ',
	#'4G':'bốn gờ',
	#'5G':'năm gờ',
 
	# Units of frequency 
	'kHz':'ki lô héc',
	'GHz':'ghi ga héc',
	'MHz':'mê ga héc',
	'Hz':'héc',
 
	# Units of data-rate 
	'Mbps':'mê ga bít trên giây',
	'Mb/s':'mê ga bít trên giây',
 
	# Units of currency 
	"đồng/" : " đồng trên ",
	"USD/" : " u ét đê trên ",
	'đ':'đồng',
	'$':'đô la',
	'USD':'u ét đê',
	'Euro':'ơ rô',
	'VNĐ':'việt nam đồng',
	'vnđ':'việt nam đồng',

	# Units of area 
	'km2':'ki lô mét vuông',
	'Km2':'ki lô mét vuông',
	'cm2':'xen ti mét vuông',
	'mm2':'mi li mét vuông',
	'm2':'mét vuông',
	'hecta':'héc ta',
 
	# Units of length 
	'km':'ki lô mét',
	'cm':'xen ti mét',
	'mm':'mi li mét',
	'nm':'na nô mét',
	'inch':'inh',
 
	# Units of volume 
	'ml':'mi li lít',
	'gr':'gam',
	'dm3':'đề xi mét khối',
	'cm3':'xen ti mét khối',
	'cc':'xê xê',
	'm3':'mét khối',
 
	# Units of weight 
	'/kg':'trên một ki lô gam',
	'kg/':'ki lô gam trên',
	'kg':'ki lô gam',
	'Kg':'ki lô gam',
	'grams':'gờ ram',
	'mg':'mi li gam',
	'kW':'ki lô goát',
 
	# Units of temperature 
	"oC" : " độ xê ",
	"°C" : " độ xê ",
	"ºC" : " độ xê ",
	"ºF" : " độ ép ",
	"oF" : " độ ép ",
	}