path:
  ckpt_path: "./output/ckpt"
  log_path: "./output/log"
  result_path: "./output/result"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
step:
  total_step: 600000
  log_step: 100
  synth_step: 2000
  val_step: 2000
  save_step: 20000
